name: Deploy to GitHub Pages
on:
  push:	
    branches:	
      - main

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-python@v2 
    - name: Install dependencies
      run: |
        pip install sphinx sphinx_rtd_theme myst_parser
    - name: sphinx build
      run: |
        sphinx-build src docs
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: git@github.com:Kartik9250/sphinx_uwu.git
        BRANCH: gh-pages
        FOLDER: docs
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}